import type { SupabaseClient } from '@supabase/supabase-js';
import type { GenerateShoppingListResponse, ShoppingListItem } from '@/lib/api/types';
import type { Database, Json } from '@/lib/supabase/types';
import { EdgeFunctionError, generateShoppingList } from '@/lib/api/edge-functions';
import { getMealPlanForWeek } from '@/lib/api/meal-plan';
import { addIsoWeeks } from '@/lib/date/iso-week';

type Pasillos = GenerateShoppingListResponse['pasillos'];

export class ShoppingListError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ShoppingListError';
  }
}

export interface ShoppingListPersistido {
  id: string
  pasillos: GenerateShoppingListResponse['pasillos']
  resumen: GenerateShoppingListResponse['resumen']
}

/**
 * Reads the persisted shopping list for a given meal plan, if one exists.
 * Business Rules: at most one list per plan — a `null` return means "not
 * generated yet", the same "not an error" convention as
 * `getMealPlanForWeek()`'s own null case.
 *
 * `resumen.total_items` is recomputed from the persisted `items` (never
 * stored itself); `coste_estimado_min/max` ARE stored (added alongside this
 * story — the generation response had them, but the table never persisted
 * them, so a revisit after generation had no cost estimate to show).
 *
 * Public method — fails fast (throws `ShoppingListError`) on a real DB
 * error, per `references/error-handling.md`.
 */
export async function getShoppingListForPlan(
  client: SupabaseClient<Database>,
  mealPlanId: string,
): Promise<ShoppingListPersistido | null> {
  const { data, error } = await client
    .from('shopping_lists')
    .select('id, items, coste_estimado_min, coste_estimado_max')
    .eq('meal_plan_id', mealPlanId)
    .maybeSingle();

  if (error) {
    throw new ShoppingListError(`No se pudo leer la lista de la compra: ${error.message}`);
  }

  if (!data) {
    return null;
  }

  // Cast, not a runtime validation — `items` is jsonb typed as `Json`, but
  // its real shape is guaranteed by `generate-shopping-list/index.ts`, the
  // only writer of this column. Same trust boundary as `meal-plan.ts`'s
  // `toRecipe()`.
  const pasillos = data.items as unknown as GenerateShoppingListResponse['pasillos'];
  const totalItems = pasillos.reduce((acc, pasillo) => acc + pasillo.items.length, 0);

  return {
    id: data.id,
    pasillos,
    resumen: {
      total_items: totalItems,
      coste_estimado_min: data.coste_estimado_min,
      coste_estimado_max: data.coste_estimado_max,
      moneda: 'EUR',
    },
  };
}

export interface EnsureShoppingListResult {
  list: ShoppingListPersistido | null
  /**
   * `true` only when THIS call generated the list (drives the one-time
   * `shopping_list_generated` capture). `false` for a read of an existing
   * list, a concurrent-render 409, or a generation failure.
   */
  generated: boolean
}

/**
 * FRESCO-367 (A4-H10): the shopping list is generated lazily on the first
 * visit to `/shopping-list`, not as a manual step. Reads the persisted list;
 * if none exists, calls `generate-shopping-list` once. A 409 means a
 * concurrent render (or another tab) already generated it — fall through to
 * the re-read. Any other failure returns `{ list: null }` so the page can
 * fall back to the manual generator button.
 *
 * The Edge Function is idempotent-guarded (`unique_plan_lista` + its own 409
 * check), so a double call is safe. Callers pass the caller's Supabase JWT.
 */
export async function ensureShoppingListForPlan(
  client: SupabaseClient<Database>,
  mealPlanId: string,
  accessToken: string | null,
): Promise<EnsureShoppingListResult> {
  const existing = await getShoppingListForPlan(client, mealPlanId);
  if (existing) {
    return { list: existing, generated: false };
  }

  let created = false;
  try {
    await generateShoppingList({ meal_plan_id: mealPlanId }, accessToken);
    created = true;
  }
  catch (error) {
    if (!(error instanceof EdgeFunctionError) || error.status !== 409) {
      console.error('[shopping-list] lazy generation failed', error);
      return { list: null, generated: false };
    }
    // 409 — already generated by a concurrent render; re-read below.
  }

  const list = await getShoppingListForPlan(client, mealPlanId);
  return { list, generated: created && list !== null };
}

/**
 * Toggles a single item's `comprado` flag via the `jsonb_set_comprado`
 * `security definer` RPC (api-contracts.md §3) — bypasses the Edge Function
 * layer entirely, the same "direct-write for an already-generated
 * resource" precedent `swapMealPlanSlots()` established. Ownership is
 * enforced inside the SQL function itself (`where ... and user_id =
 * auth.uid()`), not re-checked here.
 *
 * Business Rules: purely a local household action — never touches the menu
 * or any learning/aprendizaje data.
 */
export async function toggleShoppingListItem(
  client: SupabaseClient<Database>,
  listId: string,
  pasilloIdx: number,
  itemIdx: number,
  comprado: boolean,
): Promise<void> {
  const { error } = await client.rpc('jsonb_set_comprado', {
    p_list_id: listId,
    p_pasillo_idx: pasilloIdx,
    p_item_idx: itemIdx,
    p_comprado: comprado,
  });

  if (error) {
    throw new ShoppingListError(`No se pudo actualizar el producto: ${error.message}`);
  }
}

/**
 * Adds a suggested item (FRESCO-194's favorites-based carousel) to the
 * given pasillo via the `jsonb_add_item` `security definer` RPC — same
 * direct-write precedent as `toggleShoppingListItem`. `jsonb_add_item`
 * appends a new pasillo bucket automatically if this is the list's first
 * item for that aisle.
 */
export async function addShoppingListItem(
  client: SupabaseClient<Database>,
  listId: string,
  pasilloNombre: string,
  item: ShoppingListItem,
): Promise<void> {
  const { error } = await client.rpc('jsonb_add_item', {
    p_list_id: listId,
    p_pasillo_nombre: pasilloNombre,
    // `ShoppingListItem` is a real jsonb value (all fields serializable) —
    // the mismatch is only that its type has no index signature, not that
    // the shape is wrong.
    p_item: item as unknown as Json,
  });

  if (error) {
    throw new ShoppingListError(`No se pudo añadir el producto: ${error.message}`);
  }
}

/**
 * App-side copy of `supabase/functions/_shared/normalize.ts` — can't import
 * across the Deno/Node boundary (same reason `tests/steps/shopping-list.steps.ts`
 * keeps its own copy). Lowercase, trim, collapse whitespace, strip accents:
 * the canonical form ingredient names are compared/keyed by.
 */
export function normalizeNombre(nombre: string): string {
  return nombre
    .toLowerCase()
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/[áàä]/g, 'a')
    .replace(/[éèë]/g, 'e')
    .replace(/[íìï]/g, 'i')
    .replace(/[óòö]/g, 'o')
    .replace(/[úùü]/g, 'u')
    .replace(/ñ/g, 'n');
}

/**
 * Pure diff (FRESCO-194 "Nuevo" badge): normalized item names present in
 * `actuales` but not in `previos`. An empty `previos` yields an empty set —
 * a generated shopping list always has items, so "no prior items" means
 * "no prior list", and a first-ever list must never flag every item as new.
 */
export function diffNombresNuevos(actuales: Pasillos, previos: Pasillos): Set<string> {
  const anteriores = new Set(
    previos.flatMap(pasillo => pasillo.items).map(item => normalizeNombre(item.nombre)),
  );

  if (anteriores.size === 0) {
    return new Set();
  }

  const nuevos = new Set<string>();
  for (const pasillo of actuales) {
    for (const item of pasillo.items) {
      const clave = normalizeNombre(item.nombre);
      if (!anteriores.has(clave)) {
        nuevos.add(clave);
      }
    }
  }
  return nuevos;
}

/**
 * "Nuevo" badge data (FRESCO-194): the normalized names of items on the
 * current week's list that were NOT on the immediately-prior week's list for
 * the same user.
 *
 * Fail-soft by design — the badge is cosmetic and must never break the page
 * (same posture as the suggestions carousel). Any read error, a missing
 * prior week, or a prior week with no generated list all return an empty set.
 */
export async function getNombresNuevos(
  client: SupabaseClient<Database>,
  semanaIsoActual: string,
  pasillosActuales: Pasillos,
): Promise<Set<string>> {
  try {
    const semanaPrevia = addIsoWeeks(semanaIsoActual, -1);
    const planPrevio = await getMealPlanForWeek(client, semanaPrevia);
    if (!planPrevio) {
      return new Set();
    }

    const listaPrevia = await getShoppingListForPlan(client, planPrevio.mealPlanId);
    if (!listaPrevia) {
      return new Set();
    }

    return diffNombresNuevos(pasillosActuales, listaPrevia.pasillos);
  }
  catch (error) {
    console.error('[getNombresNuevos] failed — no "Nuevo" badges this render', error);
    return new Set();
  }
}
