import antfu from '@antfu/eslint-config';

// FRESCO-788 (audit-6 A6-A1): components that, today, reach Supabase directly.
// AGENTS.md section 10 keeps data access behind lib/, and FRESCO-810 moves each of these
// calls out. The lock below applies to every OTHER file under components/, so
// nothing new can grow the list; remove an entry here in the same change that
// removes its import.
const COMPONENTS_WITH_DIRECT_SUPABASE_ACCESS = [
  'components/admin/admin-recipe-search.tsx',
  'components/admin/delete-catalog-recipe-button.tsx',
  'components/auth/identity-cookie-sync.tsx',
  'components/landing/site-nav.tsx',
  'components/layout/sidebar-account.tsx',
  'components/menu/push-prompt-banner.tsx',
  'components/notifications/routes-notice.tsx',
  'components/onboarding/identity-step.tsx',
];

export default antfu({
  // TypeScript configuration
  typescript: {
    tsconfigPath: 'tsconfig.json',
  },

  // Less opinionated mode for easier adoption
  lessOpinionated: true,

  // Ignore patterns
  ignores: [
    'node_modules',
    'dist',
    'test-results',
    // Throwaway spike outputs — generated by scripts/spikes/*/prototype.ts on
    // run, git-ignored per each spike dir's own .gitignore. Not hand-edited.
    'scripts/spikes/**/out.*',
    'playwright-report',
    'allure-results',
    'allure-report',
    'reports',
    'cli/legacy/**',
    '*.min.js',
    // Documentation files (contain code examples that shouldn't be linted)
    '**/*.md',
    // GitHub workflows (YAML files)
    '.github/**',
    // Generated files (auto-generated, not manually edited)
    'api/openapi-types.ts',
    // FRESCO-488: joined from the Edge recipe vocabulary + lib/grocery/retail-packs.ts
    // by scripts/gen-grocery-dictionary.ts. Drift is caught by lib/grocery/dictionary.test.ts.
    'lib/grocery/ingredient-dictionary.ts',
    // FRESCO-503: matched from the datania/mercadona-catalog dataset by
    // scripts/gen-mercadona-catalog.ts. Drift is caught by
    // lib/grocery/mercadona-catalog.test.ts.
    'lib/grocery/mercadona-catalog.generated.ts',
    // FRESCO-520: matched from Consum's public storefront API by
    // scripts/gen-consum-catalog.ts. Drift is caught by
    // lib/grocery/consum-catalog.test.ts.
    'lib/grocery/consum-catalog.generated.ts',
    // Supabase Database types written by `bun run db:types` (`supabase gen
    // types typescript`, per package.json). Large machine-generated
    // snake_case file — linting it produces noise and `eslint --fix` would
    // diverge it from the generator. Found live 2026-07-31: this entry
    // previously pointed at a stale `src/types/supabase.ts` path that
    // doesn't exist in this project — `db:types` had never been run before,
    // so the mismatch stayed latent until the first real regeneration.
    'lib/supabase/types.ts',
    // boneyard-js CLI output (`npx boneyard-js build`, per its own header
    // comment "do not edit"). Same reasoning as lib/supabase/types.ts above
    // — machine-generated, re-running the CLI would just diverge it again.
    'bones/**',
    // Git worktrees placed under .claude/worktrees/ are another branch's full
    // checkout — never lint another tree from this one.
    '.claude/worktrees/**',
    // Skill directories — never lint.
    // T1 skills (.claude/skills/) and community T3/T4 skills (.agents/skills/,
    // installed at scaffold-time by `bunx skills add`) ship their .md/.json/.ts
    // as-is. ESLint must not touch them: their schemas, frontmatter, fenced
    // code blocks, and example snippets rely on exact formatting we don't own.
    '.claude/skills/**',
    '.agents/skills/**',
    // MCP reference templates — syntax-sensitive opt-in configs. Linting them
    // (e.g. toml/array-bracket-newline) corrupts the layout users copy from.
    'docs/mcp/**',
    // Supabase Edge Functions run on Deno, a separate runtime from this
    // project's Bun/Node TypeScript project (tsconfig.json excludes this
    // directory for the same reason — `npm:`-specifier imports and Deno
    // globals like `Deno.serve`/`Deno.env` aren't resolvable by this
    // project's typescript-eslint project service). Lint + type-check these
    // with `bun run deno:check` (config: supabase/functions/deno.json), run
    // as the mandatory `deno:check` CI job (FRESCO-375 / A4-H4) — not this
    // project's ESLint config.
    'supabase/functions/**',
    // Ambient declarations for tsconfig.edge-tests.json only (FRESCO-840).
    'supabase/edge-tests-types/**',
    // Impeccable design-hook cache — local-only (ignored via
    // .git/info/exclude, not the shared .gitignore), machine-written on
    // every post-edit hook run. ESLint's own ignore glob (like Prettier's
    // .prettierignore) doesn't fall back to .gitignore, so without this it
    // lints a local tool cache no one else's checkout even has.
    '.impeccable/**',
  ],

  // Custom rules
  rules: {
    // Allow console for test logging
    'no-console': 'off',

    // TypeScript specific - strict but practical
    'ts/explicit-function-return-type': 'off',
    'ts/explicit-module-boundary-types': 'off',
    'ts/no-explicit-any': 'warn',
    // Required for @atc decorator flexibility
    'ts/no-unsafe-assignment': 'off',
    'ts/no-unsafe-return': 'off',
    'ts/no-unsafe-member-access': 'off',
    'ts/no-unsafe-argument': 'off',
    'ts/no-unsafe-call': 'off',
    // Disabled: requires type info for all files including JSON
    'ts/switch-exhaustiveness-check': 'off',
    // Disabled: too strict for config files, requires explicit boolean checks
    'ts/strict-boolean-expressions': 'off',

    // Node.js globals - standard in Bun/Node environment
    'node/prefer-global/buffer': 'off',
    'node/prefer-global/process': 'off',

    // Style preferences
    'style/semi': ['error', 'always'],
    'style/quotes': ['error', 'single'],
    'style/comma-dangle': ['error', 'always-multiline'],
    'style/max-statements-per-line': 'off',
    // Disabled: conflicts with Prettier YAML formatting (Prettier owns YAML style)
    'yaml/flow-mapping-curly-spacing': 'off',
    // Disabled: conflicts with Prettier JSONC formatting (Prettier adds trailing commas
    // in opencode.jsonc which this rule rejects). Prettier owns JSONC style.
    'jsonc/comma-dangle': 'off',

    // Allow unused vars with underscore prefix
    'unused-imports/no-unused-vars': [
      'warn',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      },
    ],
  },
}, {
  // --- cli/ IMPORT CLOSURE (updater self-update invariant) ---
  //
  // `cli/` is the updater's self-update component: `runUpdate` refreshes those
  // files in place and re-execs the process BEFORE any other component is
  // synced (cli/lib/updater-core.ts, "SELF-UPDATE (before Phase 2)"). A repo
  // several releases behind therefore runs the NEW `cli/` against its OWN, old
  // copy of every sibling directory.
  //
  // So an import that escapes `cli/` is not a style question: it bricks the
  // update path for anyone jumping more than one release. It happened in the
  // QA boilerplate: `cli/` imported `../scripts/agent-compatibility.ts`, the
  // re-exec died on `Cannot find module`, and `bun run up`, `up --rollback`,
  // `setup` and `setup:doctor` all went down together, since the failure is at
  // module load and the rollback path shares the same entrypoint.
  //
  // Shared code goes in `cli/lib/`. A `scripts/` file that needs it imports
  // FROM `cli/` (that direction is safe: `scripts/` is synced later, never
  // re-exec'd mid-run). `api/`, `src/`, `config/` and `tests/` are listed for
  // the scaffolded project this config travels into; they are equally absent
  // at re-exec time.
  files: ['cli/**/*.ts'],
  rules: {
    // cli/ is synced wholesale into downstream projects and must type-check
    // under THEIR tsconfig and @types/node (see cli/updater-host-types.test.ts).
    // Both autofixes are valid here but not there: a cast that is redundant
    // under this repo's @types/node (`execSync(...) as unknown as Buffer`) can
    // be required under another version, and `Object.hasOwn` needs a host with
    // `lib` ES2022. Keep the portable form in cli/.
    'ts/no-unnecessary-type-assertion': 'off',
    'e18e/prefer-object-has-own': 'off',
    'no-restricted-imports': ['error', {
      patterns: [{
        group: [
          '../scripts/**',
          '../../scripts/**',
          '../../../scripts/**',
          '../../../../scripts/**',
          '../packages/**',
          '../../packages/**',
          '../../../packages/**',
          '../../../../packages/**',
          '../api/**',
          '../../api/**',
          '../../../api/**',
          '../../../../api/**',
          '../src/**',
          '../../src/**',
          '../../../src/**',
          '../../../../src/**',
          '../config/**',
          '../../config/**',
          '../../../config/**',
          '../../../../config/**',
          '../tests/**',
          '../../tests/**',
          '../../../tests/**',
          '../../../../tests/**',
          '@/*',
          '@api/*',
          '@schemas/*',
          '@utils/*',
        ],
        message: 'cli/ must be import-closed: the updater re-execs the new cli/ before other components are synced, so an import that escapes cli/ breaks `bun run up` for repos more than one release behind. Move the shared module into cli/lib/ instead.',
      }],
    }],
  },
}, {
  // --- AGENTS.md section 10, enforced for product code (FRESCO-788, audit-6 A6-A1) ---
  //
  // Both rules were oral convention until audit-6 counted 31 functions with 3 or
  // more positional parameters in product code; they are 0 now and this keeps
  // them there. Scope is app/, components/ and lib/. scripts/ and cli/ are
  // internal tooling (145 such signatures when this was measured) and are exempt
  // on purpose; tests and generated files are not product code either.
  files: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}', 'lib/**/*.{ts,tsx}'],
  ignores: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
  rules: {
    'max-params': ['error', 2],
    // FRESCO-809 (audit-6 A6-A5/A6-A6): the closing criterion was "no product
    // function above complexity 25, no product file above 450 lines" and it was
    // reached by hand; these two keep it there. `complexity` replaces the earlier
    // `warn` at 15 (a rule has one severity per file): the 25 ceiling blocks, and
    // anything between 16 and 25 is no longer surfaced in the editor.
    'complexity': ['error', 25],
    'max-lines': ['error', 450],
  },
}, {
  // Generated by `supabase gen types`, never edited by hand, so a line cap says
  // nothing about it.
  files: ['lib/supabase/types.ts'],
  rules: {
    'max-lines': 'off',
  },
}, {
  // --- Component layer lock (FRESCO-788) ---
  //
  // components/ must not import the Supabase wrapper or the SDK: data access lives
  // behind lib/ (AGENTS.md section 10). The files in COMPONENTS_WITH_DIRECT_SUPABASE_ACCESS
  // already do and are left alone until FRESCO-810 moves their calls; every other
  // file under components/ is locked.
  files: ['components/**/*.{ts,tsx}'],
  ignores: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', ...COMPONENTS_WITH_DIRECT_SUPABASE_ACCESS],
  rules: {
    'no-restricted-imports': ['error', {
      patterns: [{
        group: ['@/lib/supabase', '@/lib/supabase/*', '@supabase/*'],
        message: 'Components must not reach Supabase directly (AGENTS.md section 10: data access lives behind lib/). Put the call in lib/ and import that. This file is not on COMPONENTS_WITH_DIRECT_SUPABASE_ACCESS in eslint.config.js: the list only shrinks (FRESCO-810), it does not grow.',
      }],
    }],
  },
}, {
  // --- lib/ does not depend on the UI layers (FRESCO-810, ADR-0041) ---
  //
  // `lib/` is framework-agnostic data and domain code; the UI depends on it, never
  // the other way round. `lib/fixtures/page-shells.tsx` (13 component imports) and
  // an email template that read two constants from a component were the last two
  // inversions; both moved, and this keeps `lib/` clean.
  files: ['lib/**/*.{ts,tsx}'],
  ignores: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
  rules: {
    'no-restricted-imports': ['error', {
      patterns: [{
        group: ['@/components', '@/components/*', '@/app', '@/app/*'],
        message: 'lib/ must not import from components/ or app/ (ADR-0041): the UI depends on lib/, never the reverse. Move the shared value into lib/ and import it from there.',
      }],
    }],
  },
});
