/* qa-guide-snapshot: stack=nextjs-app-router+supabase+edge-functions, generated=2026-08-01 */
import type { Metadata } from 'next';
import { Database, FlaskConical, Globe, KeyRound, Server } from 'lucide-react';

import { CodeBlock } from '@/components/qa/code-block';
import { RequestCard } from '@/components/qa/request-card';
import { buttonVariants } from '@/components/ui/button';
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

/**
 * `/qa` — public "Software Testability Guide for QA" page, generated by the
 * `testability-guide` skill (`.session/testability-guide/plan.md`). This is
 * a course final-project demo surface, not an internal ops page — no auth
 * gate, meant to let an external evaluator test Fresco at DB/API/UI level
 * without any hand-holding.
 *
 * Re-runs of the skill detect drift via the `qa-guide-snapshot` comment above
 * and propose surgical patches instead of a full rewrite — do not remove it.
 */

export const metadata: Metadata = {
  title: 'Guía de testeabilidad para QA — Fresco',
  description: 'Cómo probar Fresco a nivel de base de datos, API y UI.',
};

const SUPABASE_PROJECT_REF = 'jdqemhewjrjuopssdurn';
const FUNCTIONS_BASE_URL = `https://${SUPABASE_PROJECT_REF}.functions.supabase.co`;

const architectureDiagram = `Navegador
  |
  v
Next.js App Router (Vercel)
  |
  |-- Supabase Auth (JWT)
  |-- Supabase Postgres + RLS
  |
  v
Edge Functions (Deno, server-only)   <-- 100% determinista, sin llamadas a IA`;

export default function QaGuidePage() {
  const credentialsUrl = process.env.NEXT_PUBLIC_QA_CREDENTIALS_URL;

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-8 px-4 py-12">
      {/* 1. Header */}
      <header>
        <h1 className="text-h2">Guía de testeabilidad para QA</h1>
        <p className="mt-2 text-body-md text-tertiary">
          Fresco es una app de planificación de menús semanales construida con Next.js (App Router) y
          Supabase (Postgres, Auth y Edge Functions), con generación de menú 100% determinista. Esta
          página reúne todo lo necesario para que un evaluador externo pueda probar la aplicación a
          nivel de base de datos, API y UI, sin depender de nadie del equipo.
        </p>
      </header>

      {/* 2. Arquitectura */}
      <section aria-labelledby="qa-architecture-heading">
        <h2 id="qa-architecture-heading" className="text-h3">Arquitectura</h2>
        <p className="mt-2 text-body-sm text-tertiary">
          Frontend Next.js desplegado en Vercel, backend en Supabase (Postgres + Auth + Edge
          Functions). Selección de menú, explicación de aprendizaje y lista de la compra son
          100% deterministas — sin llamadas a modelos de IA en producción.
        </p>
        <CodeBlock code={architectureDiagram} lang="text" className="mt-3" />

        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Globe className="size-4 text-primary" aria-hidden="true" />
                <CardTitle>Local</CardTitle>
              </div>
              <CardDescription>http://localhost:3000</CardDescription>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Server className="size-4 text-primary" aria-hidden="true" />
                <CardTitle>PRE / staging</CardTitle>
              </div>
              <CardDescription>
                https://fresco-pre.vercel.app sigue la rama
                {' '}
                <code>staging</code>
                {' '}
                y https://fresco-pro.vercel.app la rama
                {' '}
                <code>main</code>
                , cada una atada a su despliegue más reciente vía Vercel Git Branch. Son
                entornos distintos, aunque a veces apunten al mismo commit tras una promoción.
              </CardDescription>
            </CardHeader>
          </Card>
        </div>
      </section>

      {/* 3. Usuarios demo */}
      <section aria-labelledby="qa-demo-users-heading">
        <h2 id="qa-demo-users-heading" className="text-h3">Usuarios demo</h2>
        <p className="mt-2 text-body-sm text-tertiary">
          Las cuentas reales viven en variables de entorno, nunca en esta página. Estos son los slots
          disponibles:
        </p>

        <div className="mt-3 overflow-x-auto rounded-md border border-border">
          <table className="w-full text-left text-body-sm">
            <thead className="bg-surface text-caption uppercase text-tertiary">
              <tr>
                <th className="px-3 py-2">Cuenta</th>
                <th className="px-3 py-2">Variables de entorno</th>
                <th className="px-3 py-2">Descripción</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <tr>
                <td className="px-3 py-2">Local (Free)</td>
                <td className="px-3 py-2 font-mono text-caption">DEV_USER_EMAIL / DEV_USER_PASSWORD</td>
                <td className="px-3 py-2 text-tertiary">Cuenta de plan Free para el entorno local.</td>
              </tr>
              <tr>
                <td className="px-3 py-2">PRE (Free)</td>
                <td className="px-3 py-2 font-mono text-caption">PRE_USER_EMAIL / PRE_USER_PASSWORD</td>
                <td className="px-3 py-2 text-tertiary">Cuenta de plan Free en el entorno PRE/staging.</td>
              </tr>
              <tr>
                <td className="px-3 py-2">Pro (dedicada)</td>
                <td className="px-3 py-2 font-mono text-caption">PRO_USER_EMAIL / PRO_USER_PASSWORD</td>
                <td className="px-3 py-2 text-tertiary">
                  Cuenta Pro con historial real, para probar el aprendizaje de Fresco (FRESCO-22 /
                  ADR-0001).
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-4 flex items-center gap-3">
          {credentialsUrl
            ? (
                <a
                  href={credentialsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  data-testid="qa_credentials_cta"
                  className={buttonVariants({ variant: 'action', size: 'md' })}
                >
                  Ver credenciales reales
                </a>
              )
            : (
                <p data-testid="qa_credentials_fallback" className="flex items-center gap-2 text-body-sm text-tertiary">
                  <KeyRound className="size-4" aria-hidden="true" />
                  Credenciales: pedir acceso al Jira Epic FRESCO-25.
                </p>
              )}
        </div>
      </section>

      {/* 4. Testing a nivel DB */}
      <section aria-labelledby="qa-db-heading">
        <h2 id="qa-db-heading" className="text-h3">Testing a nivel DB</h2>
        <div className="mt-2 flex items-start gap-2">
          <Database className="mt-1 size-4 shrink-0 text-primary" aria-hidden="true" />
          <p className="text-body-sm text-tertiary">
            Este repositorio ya tiene configurado el MCP de Supabase (
            <code>.mcp.json</code>
            , servidor
            {' '}
            <code>supabase</code>
            ). Cualquier agente de IA con acceso al repo puede consultar la base de datos directamente
            con
            {' '}
            <code>mcp__supabase__execute_sql</code>
            ,
            {' '}
            <code>list_tables</code>
            {' '}
            o
            {' '}
            <code>get_logs</code>
            , siempre scopeado al proyecto
            {' '}
            <code>{SUPABASE_PROJECT_REF}</code>
            .
          </p>
        </div>
        <p className="mt-3 text-body-sm text-tertiary">
          Para un tester humano (sin agente), Supabase Studio expone el mismo proyecto con la clave
          publishable/anon del lado cliente (RLS activo — nunca la service role key):
        </p>
        <CodeBlock code={`https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}`} lang="text" className="mt-2" />
      </section>

      {/* 5. Testing a nivel API */}
      <section aria-labelledby="qa-api-heading">
        <h2 id="qa-api-heading" className="text-h3">Testing a nivel API</h2>
        <p className="mt-2 text-body-sm text-tertiary">
          Las 4 Edge Functions reales de Fresco. Todas requieren un JWT de Supabase Auth en el header
          {' '}
          <code>Authorization: Bearer &lt;token&gt;</code>
          {' '}
          — sin él, responden
          {' '}
          <code>401</code>
          .
        </p>

        <div className="mt-4 flex flex-col gap-4">
          <RequestCard
            name="generate-meal-plan"
            description="Selecciona el menú semanal (7 días x 3 comidas) con un algoritmo determinista sobre el catálogo filtrado (ADR-0005). La explicación de aprendizaje de un usuario Pro con historial real también es determinista — sin llamadas a IA en ningún paso."
            method="POST"
            path={`${FUNCTIONS_BASE_URL}/generate-meal-plan`}
            body={{ semana_iso: '2026-W32', fecha_inicio: '2026-08-03' }}
          />
          <RequestCard
            name="generate-shopping-list"
            description="Genera la lista de la compra agrupada por pasillo a partir de un meal plan existente."
            method="POST"
            path={`${FUNCTIONS_BASE_URL}/generate-shopping-list`}
            body={{ meal_plan_id: '00000000-0000-4000-8000-000000000000' }}
          />
          <RequestCard
            name="reassign-guest-data"
            description="Reasigna los datos de una sesión de invitado (guest) a una cuenta real ya existente."
            method="POST"
            path={`${FUNCTIONS_BASE_URL}/reassign-guest-data`}
            body={{ email: 'usuario@ejemplo.com', password: 'contraseña-de-ejemplo' }}
          />
          <RequestCard
            name="update-recipe-status"
            description="Actualiza el estado de una receta dentro de un slot del menú (cocinada, descartada, sustituida...)."
            method="PATCH"
            path={`${FUNCTIONS_BASE_URL}/update-recipe-status`}
            body={{ meal_plan_recipe_id: '00000000-0000-4000-8000-000000000001', estado: 'cocinada', rating: 5 }}
          />
        </div>
      </section>

      {/* 6. Testing a nivel UI */}
      <section aria-labelledby="qa-ui-heading">
        <h2 id="qa-ui-heading" className="text-h3">Testing a nivel UI</h2>
        <div className="mt-2 flex items-start gap-2">
          <FlaskConical className="mt-1 size-4 shrink-0 text-primary" aria-hidden="true" />
          <p className="text-body-sm text-tertiary">
            Playwright ya está instalado (
            <code>bun run test:e2e</code>
            ). Los escenarios ya escritos viven en
            {' '}
            <code>.context/qa/regression.feature</code>
            {' '}
            (Gherkin, en español). Un agente de IA puede además manejar la UI en vivo con el tool
            {' '}
            <code>playwright-cli</code>
            {' '}
            — ya usado durante todo el desarrollo de este proyecto — sin más setup que tener
            {' '}
            <code>bun run dev</code>
            {' '}
            corriendo.
          </p>
        </div>
      </section>

      {/* 7. Footer */}
      <footer className="border-t border-border pt-4 text-caption text-tertiary">
        Esta página es generada y mantenida por la skill
        {' '}
        <code>testability-guide</code>
        .
      </footer>
    </div>
  );
}
