#!/usr/bin/env bun

// FRESCO-488 — generator for `lib/grocery/ingredient-dictionary.ts`.
//
// The canonical ingredient name set + aisle already exist in the Edge
// function's recipe vocabulary (`supabase/functions/generate-shopping-list/`):
// `BASE_QUANTITIES` (name -> recipe portion) and `INGREDIENT_AISLE` (via
// `pasilloFor`). Re-typing ~200 rows by hand would just create a second copy
// to drift. Instead this script joins that vocabulary onto the hand-curated
// overlay in `lib/grocery/retail-packs.ts` (retail pack sizes, search-term
// hints, synonyms) and emits the merged dictionary.
//
// Run: bun scripts/gen-grocery-dictionary.ts
// The output file is committed. `lib/grocery/dictionary.test.ts` fails if it
// drifts from a fresh run (same pattern as scripts/check-*-drift.ts).

import type { CanonicalIngredient } from '../lib/grocery/types.ts';
import {
  DEFAULT_PACK_BY_UNIT,
  RETAIL_PACK_OVERRIDE,
  SEARCH_TERM_OVERRIDE,
  SYNONYM_OVERRIDE,
} from '../lib/grocery/retail-packs.ts';
import { pasilloFor } from '../supabase/functions/generate-shopping-list/aisle-pricing.ts';
import { BASE_QUANTITIES } from '../supabase/functions/generate-shopping-list/consolidator.ts';

// The 8 ingredients `pasilloFor` returns 'Otros' for — no `INGREDIENT_AISLE` row.
const AISLE_OVERRIDE: Record<string, CanonicalIngredient['pasillo']> = {
  'bacon': 'Charcutería y embutidos',
  'mantequilla': 'Lácteos y huevos',
  'muslo de pollo': 'Carnes y aves',
  'nata liquida': 'Lácteos y huevos',
  'pimenton': 'Aceites/vinagres/condimentos',
  'pimienta negra': 'Aceites/vinagres/condimentos',
  'tomate cherry': 'Frutas y verduras',
  'tomate frito': 'Conservas y salsas',
};

// Accent-restored display names — `BASE_QUANTITIES` keys are accent-stripped
// (they are `normalizeNombre` output). Default display = the key itself.
const ACCENT_DISPLAY: Record<string, string> = {
  'aji amarillo': 'ají amarillo',
  'atun': 'atún',
  'atun en lata': 'atún en lata',
  'azafran': 'azafrán',
  'brocoli': 'brócoli',
  'calabacin': 'calabacín',
  'champinones': 'champiñones',
  'esparragos': 'espárragos',
  'esparragos trigueros': 'espárragos trigueros',
  'higado': 'hígado',
  'jamon': 'jamón',
  'jamon cocido': 'jamón cocido',
  'jamon iberico': 'jamón ibérico',
  'jamon serrano': 'jamón serrano',
  'judias verdes': 'judías verdes',
  'limon': 'limón',
  'maiz blanco': 'maíz blanco',
  'melon': 'melón',
  'oregano': 'orégano',
  'pimenton': 'pimentón',
  'pimenton dulce': 'pimentón dulce',
  'pimenton picante': 'pimentón picante',
  'platano': 'plátano',
  'rucula': 'rúcula',
  'salmon': 'salmón',
  'salmon ahumado': 'salmón ahumado',
  'sesamo': 'sésamo',
  'tortilla de maiz': 'tortilla de maíz',
};

function buildEntry(clave: string): CanonicalIngredient {
  const porcion = BASE_QUANTITIES[clave];
  const canonico = ACCENT_DISPLAY[clave] ?? clave;
  const envaseVenta
    = RETAIL_PACK_OVERRIDE[clave]
      ?? DEFAULT_PACK_BY_UNIT[porcion.unidad]
      ?? { cantidad: 1, unidad: porcion.unidad };
  return {
    clave,
    canonico,
    pasillo: AISLE_OVERRIDE[clave] ?? pasilloFor(clave),
    porcionReceta: { cantidad: porcion.cantidad, unidad: porcion.unidad },
    envaseVenta,
    sinonimos: SYNONYM_OVERRIDE[clave] ?? [],
    terminoBusqueda: SEARCH_TERM_OVERRIDE[clave] ?? canonico,
  };
}

export function buildDictionary(): Record<string, CanonicalIngredient> {
  const out: Record<string, CanonicalIngredient> = {};
  for (const clave of Object.keys(BASE_QUANTITIES).sort((a, b) => a.localeCompare(b, 'es'))) {
    out[clave] = buildEntry(clave);
  }
  return out;
}

export function renderFile(dict: Record<string, CanonicalIngredient>): string {
  const entries = Object.values(dict)
    .map(e => `  ${JSON.stringify(e.clave)}: ${JSON.stringify(e)},`)
    .join('\n');
  return `// GENERATED by scripts/gen-grocery-dictionary.ts — do not edit by hand.
// Source: Edge \`BASE_QUANTITIES\` + \`pasilloFor\` joined with the hand-curated
// overlay in \`lib/grocery/retail-packs.ts\`. Regenerate: bun scripts/gen-grocery-dictionary.ts
// Drift is caught by lib/grocery/dictionary.test.ts.

import type { CanonicalIngredient } from './types';

/** Canonical Fresco ingredient vocabulary, keyed by normalized name. */
export const INGREDIENT_DICTIONARY: Record<string, CanonicalIngredient> = {
${entries}
};

/** Sorted list of every canonical key — handy for parity checks and iteration. */
export const CANONICAL_KEYS: readonly string[] = Object.keys(INGREDIENT_DICTIONARY);
`;
}

if (import.meta.main) {
  const target = new URL('../lib/grocery/ingredient-dictionary.ts', import.meta.url);
  const contents = renderFile(buildDictionary());
  await Bun.write(target, contents);
  console.log(`Wrote ${Object.keys(buildDictionary()).length} entries to lib/grocery/ingredient-dictionary.ts`);
}
